---
title: "Capturing effects of class sizes with classroom performacne"
author: "Connor Rosenberg"
date: "1/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#Required Packages

library("AER")
library("ggplot2")
library("car")
library("dplyr")
library("plotly")

```

```{r, include=FALSE}
#Prepare Data

data("STAR")

star = data.frame( "gender" = STAR$gender, "ethnicity" = STAR$ethnicity, "star1" = STAR$star1, "math1" = STAR$math1)


star = star[complete.cases(star),] #Eliminate all cases w/ NA
```

```{r, include=FALSE}
#Check data & objects

#str(star)

star$gender = as.factor(star$gender)
star$ethnicity = as.factor(star$ethnicity)
star$star1 = as.factor(star$star1)
star$lunch1 = as.factor(star$lunch1)
star$degree1 = as.factor(star$degree1)
star$ladder1 = as.factor(star$ladder1)
star$tethnicity1 = as.factor(star$tethnicity1)
star$system1 = as.factor(star$system1)
star$schoolid1 = as.factor(star$schoolid1)

```


```{r, include= FALSE}
#Set colors for pretty pictures

color2 = c("#FF6868", "#54B7FF")
color3 = c("#FF6868", "#54B7FF", "97FF68")
color4 = c("#FF6868", "#54B7FF", "97FF68", "#A168FF")
color5 = c("#FF6868", "#54B7FF", "97FF68", "#A168FF", "#FFB768")
color5 = c("#FF6868", "#54B7FF", "97FF68", "#A168FF", "#FFB768", "#FFE068")
 

#NOTE: colors will be assigned to factors in alphabetical order
```


```{r, include=FALSE}
#Task 1 Summary Statistics:
#NOTE: Please save all figures as objects to be called later in the report
#NOTE: Use plotly package to make everything consistant https://plot.ly/r

summary(star)

#Boxplot of Gender
count = data.frame(table(star$gender))
pieGender = plot_ly(count, labels = ~Var1, values = ~Freq, type = 'pie') %>%
  layout(title = "Gender of Participating Studnets")
pieGender
```


```{r, include=FALSE}
#Task 4
```


```{r, include = FALSE}
#Fitting the model

# Test for variance homogeneity
leveneTest(math1~star1, data = star) #Equal Variacnes


#One-Way ANOVA for STAR1
reg1 = lm(math1~star1, data = star)
summary(reg1)
anova1 = anova(reg1)
anova1
boxplot(star$math1~star$star1)

plot(reg1,2)
plot(reg1)


#Plot of boxplot of math scores broken by class type
box1 = plot_ly(star, y = ~math1, color = ~star1, type = "box")
box1
```

```{r, include = FALSE}
#Write the reprt below
```


# Introduction

## Background

##Questions of Interest

#Methods & Analysis

##Descriptive Analysis



